name: Doxygen

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Doxygen and Github Pages
      uses: AgarwalSaurav/ghaction-doxygen-ghpages@v2.2.0
